version: "3.8"

services:

  accounts:
    image: jpelegrino/accounts
    ports:
      - "8080:8080"
    networks:
      - eazybank-network
    
  loans:
    image: jpelegrino/loans
    ports:
      - "8090:8090"
    networks:
      - eazybank-network
    
  cards:
    image: jpelegrino/cards
    ports:
      - "9000:9000"
    networks:
      - eazybank-network
    
networks:
  eazybank-network: